package define

const ANNOTATIONRESPONSE = "ANNOTATION_RESPONSE"

const ANNOTATIONTOKEN = "ANNOTATION_AUTH_BEARER"

const ANNOTATIONUID= "ANNOTATION_STUID"

const ANNOTATIONUSERNAME = "ANNOTATION_USER_NAME"

const ANNOTATIONPOLICY = "ANNOTATION_POLICY"

const ANNOTATIONLOGINSTATUS ="LOGIN_STATUS"